package scanner

import (
	"bufio"
	"bytes"
	"context"
	"crypto/tls"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"net"
	"strconv"
	"strings"
	"time"
)

// maxGMPResponseBytes bounds a single GMP response so a runaway gvmd stream
// cannot exhaust memory. Full reports are large but stay well under this.
const maxGMPResponseBytes = 512 << 20

// gmpConn is a minimal Greenbone Management Protocol client.
//
// gvmd speaks plain XML request/response over its UNIX socket and TLS over port
// 9390, so the pipeline talks to it directly instead of shelling out to
// gvm-cli. gvm-tools refuses to start under uid 0 (its do_not_run_as_root
// guard), while the engine container runs as root by design — the subprocess
// path could never authenticate from inside the image.
type gmpConn struct {
	conn net.Conn
	r    *bufio.Reader
}

func dialGMP(ctx context.Context, cfg Config) (*gmpConn, error) {
	var (
		conn net.Conn
		err  error
	)
	if strings.TrimSpace(cfg.GVMSocket) != "" {
		conn, err = (&net.Dialer{}).DialContext(ctx, "unix", cfg.GVMSocket)
	} else {
		// gvmd serves GMP with the self-signed certificate generated by the
		// Greenbone stack, and gvm-tools' TLS transport did not verify it
		// either. The endpoint is an internal, operator-configured service.
		dialer := &tls.Dialer{Config: &tls.Config{InsecureSkipVerify: true}}
		conn, err = dialer.DialContext(ctx, "tcp", net.JoinHostPort(cfg.GVMHost, strconv.Itoa(cfg.GVMPort)))
	}
	if err != nil {
		return nil, err
	}
	return &gmpConn{conn: conn, r: bufio.NewReaderSize(conn, 64<<10)}, nil
}

func (c *gmpConn) Close() error { return c.conn.Close() }

// exec sends one GMP command and returns the raw XML of the single response
// document gvmd writes back. Callers hold the connection for the whole scan:
// GMP authentication is per connection, not per command.
func (c *gmpConn) exec(ctx context.Context, request string) ([]byte, error) {
	if deadline, ok := ctx.Deadline(); ok {
		_ = c.conn.SetDeadline(deadline)
	} else {
		_ = c.conn.SetDeadline(time.Time{})
	}
	// Unblock a pending read as soon as the scan context is cancelled.
	defer context.AfterFunc(ctx, func() { _ = c.conn.SetDeadline(time.Unix(1, 0)) })()
	if _, err := io.WriteString(c.conn, request); err != nil {
		return nil, err
	}
	return c.readDocument()
}

func (c *gmpConn) readDocument() ([]byte, error) {
	var buf bytes.Buffer
	chunk := make([]byte, 32<<10)
	for {
		n, err := c.r.Read(chunk)
		if n > 0 {
			buf.Write(chunk[:n])
			if buf.Len() > maxGMPResponseBytes {
				return nil, fmt.Errorf("GMP response exceeded %d bytes", maxGMPResponseBytes)
			}
			if completeXMLDocument(buf.Bytes()) {
				return buf.Bytes(), nil
			}
		}
		if err != nil {
			if errors.Is(err, io.EOF) {
				return nil, errors.New("gvmd closed the GMP connection before a complete response")
			}
			return nil, err
		}
	}
}

func (c *gmpConn) authenticate(ctx context.Context, user, pass string) error {
	resp, err := c.exec(ctx, "<authenticate><credentials><username>"+xmlEscape(user)+
		"</username><password>"+xmlEscape(pass)+"</password></credentials></authenticate>")
	if err != nil {
		return err
	}
	return gmpStatusError(resp)
}

// completeXMLDocument reports whether buf already holds one whole XML element.
// GMP is strictly request/response, so the first complete top-level element is
// the response and nothing trails it.
func completeXMLDocument(buf []byte) bool {
	d := xml.NewDecoder(bytes.NewReader(buf))
	depth := 0
	for {
		tok, err := d.Token()
		if err != nil {
			return false
		}
		switch tok.(type) {
		case xml.StartElement:
			depth++
		case xml.EndElement:
			depth--
			if depth == 0 {
				return true
			}
		}
	}
}

// gmpStatusError turns a non-2xx GMP status attribute into an error. gvmd
// answers protocol failures (bad credentials, missing permissions, malformed
// commands) with a 4xx/5xx status on an otherwise well-formed response.
func gmpStatusError(data []byte) error {
	code, text := gmpStatus(data)
	if code == "" {
		return errors.New("gvmd returned a response without a GMP status")
	}
	if strings.HasPrefix(code, "2") {
		return nil
	}
	if text == "" {
		text = "unspecified GMP error"
	}
	return fmt.Errorf("gvmd responded %s: %s", code, text)
}

func gmpStatus(data []byte) (code, text string) {
	d := xml.NewDecoder(bytes.NewReader(data))
	for {
		tok, err := d.Token()
		if err != nil {
			return "", ""
		}
		s, ok := tok.(xml.StartElement)
		if !ok {
			continue
		}
		for _, a := range s.Attr {
			switch a.Name.Local {
			case "status":
				code = a.Value
			case "status_text":
				text = a.Value
			}
		}
		return code, text
	}
}

// xmlIDByExactName returns the id of the first element whose <name> child
// matches want exactly, falling back to the first element of that kind. GMP
// name filters match substrings, so the exact match keeps a feed that ships
// "Full and fast" alongside similarly named configs from picking the wrong one.
func xmlIDByExactName(data []byte, element, want string) string {
	d := xml.NewDecoder(bytes.NewReader(data))
	first := ""
	for {
		tok, err := d.Token()
		if err != nil {
			return first
		}
		s, ok := tok.(xml.StartElement)
		if !ok || s.Name.Local != element {
			continue
		}
		id := ""
		for _, a := range s.Attr {
			if a.Name.Local == "id" {
				id = a.Value
			}
		}
		var v struct {
			Name string `xml:"name"`
		}
		if err := d.DecodeElement(&v, &s); err != nil {
			return first
		}
		if id == "" {
			continue
		}
		if strings.EqualFold(strings.TrimSpace(v.Name), want) {
			return id
		}
		if first == "" {
			first = id
		}
	}
}
