import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api } from "@/api/client";
import type { CoverageProof, DiscoveryRevision } from "@/types/api";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export function WorkflowProof({ scanId, running, proof }: {scanId: string; running: boolean; proof?: CoverageProof}) {
 const [selected, setSelected] = useState<string[]>([]);
 const [revision, setRevision] = useState<DiscoveryRevision>();
 const [started, setStarted] = useState("");
 const discovery = useQuery({queryKey:["discovery-preview",scanId,running],queryFn:()=>api.discoveryPreview(scanId),enabled:!!proof?.expanded_enabled,retry:false});
 useEffect(()=>{if(discovery.data?.approved_revision){setRevision(discovery.data.approved_revision);setSelected(discovery.data.approved_revision.selected_ids)}},[discovery.data]);
 const approval = useMutation({mutationFn:()=>api.approveDiscovery(scanId,discovery.data!.fingerprint,selected),onSuccess:setRevision});
 const start = useMutation({mutationFn:()=>api.startScan({assessment:revision!.plan.config,plan_fingerprint:revision!.plan.fingerprint,targets:revision!.plan.config.assessment_targets.map(t=>t.value)}),onSuccess:r=>setStarted(r.instance_id)});
 const [metric,setMetric]=useState<{name:string;scanner?:string;label:string}|null>(null);
 const [trace,setTrace]=useState<string|null>(null);
 if (!proof) return null;
 return <Card><CardHeader><CardTitle className="text-sm">Recorded coverage</CardTitle><CardDescription>Counts refer to saved inventory and scanner evidence. Submission and batch completion do not prove every check ran.</CardDescription></CardHeader><CardContent className="space-y-4">
 <div className="grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">{([
 ["Inventory requests",proof.discovered,"discovered"],["Observed requests",proof.observed,"observed"],["Approved requests",proof.approved,"approved"],["Eligible requests",proof.eligible,"eligible"],["Supplied seeds",proof.seeds,"seeds"],["Candidate hosts",proof.candidates,"candidates"],["Observed hosts",proof.hosts,"hosts"],["Services",proof.services,"services"],["TLS services",proof.tls_services,"tls_services"],["Forms",proof.forms,"forms"],["Parameterized requests",proof.parameterized,"parameterized"],["Observed with auth",proof.observed_with_auth,"observed_with_auth"]
 ] as const).map(([label,count,name])=><button type="button" className="rounded border p-2 text-left hover:bg-muted" key={label} onClick={()=>setMetric({name,label})}><p className="text-muted-foreground">{label}</p><p className="font-medium underline">{count}</p></button>)}</div>
 <div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr>{["Scanner","Enabled templates","Selected","Submitted","Acknowledged","Observed active endpoints","Batch completed","Proven completed requests","Failed","Skipped","Unknown"].map(label=><th className="whitespace-nowrap p-2" key={label}>{label}</th>)}</tr></thead><tbody>{(proof.scanners ?? []).map(row=><tr className="border-t" key={row.scanner}><td className="p-2">{row.scanner}</td>{([
 ["enabled_templates",row.enabled_templates],["selected",row.selected],["submitted",row.submitted],["acknowledged",row.acknowledged],["exercised",row.exercised],["batch_completed",row.batch_completed],["completed",row.completed],["failed",row.failed],["skipped",row.skipped],["unknown",row.unknown]
 ] as const).map(([name,value])=><td className="whitespace-nowrap p-2" key={name}>{value==null?"NOT TRACKED":<button type="button" className="underline" onClick={()=>setMetric({name,scanner:row.scanner,label:`${row.scanner} · ${name.replaceAll("_"," ")}`})}>{value}</button>}</td>)}</tr>)}</tbody></table></div>
 {(proof.identity_discovery ?? []).map(identity=><div className="space-y-1 rounded border p-2 text-xs" key={`${identity.auth_context_id}:${identity.attempt_id}`}><p className="font-medium">Browser discovery · {identity.identity} {identity.role && `(${identity.role})`}</p><p>{identity.status} · authentication {identity.auth_state || "NOT TRACKED"} · {identity.observed_requests} observed requests</p><p>{identity.reason}</p><p className="break-all text-muted-foreground">Context: {identity.auth_context_id} · Attempt: {identity.attempt_id || "NOT TRACKED"} · Evidence: {identity.evidence_reference || "Not provided"}</p></div>)}
 {(proof.authorization_results ?? []).length > 0 && <div className="space-y-2 border-t pt-3"><p className="text-sm font-medium">Supplied role access expectations</p><p className="text-xs text-muted-foreground">Checks use supplied controlled resources. Unknown results do not establish access or denial.</p>{proof.authorization_results!.map((result,i)=><div className="space-y-1 rounded border p-2 text-xs" key={`${result.endpoint_id}-${i}`}><p>{result.identity} {result.role && `(${result.role})`} · {result.status}</p><p className="break-all font-mono">{result.method} {result.url || "Not provided"}</p><p>Expected: {result.expected} · Observed: {result.observed || "Unknown"} · HTTP: {result.response_code ?? "Not recorded"}</p><p>{result.reason}</p><p className="break-all text-muted-foreground">Context: {result.auth_context_id || "Not verified"} · Operation: {result.operation_id} · Fixture: {result.fixture_ref}</p><p className="break-all text-muted-foreground">Evidence: {result.evidence_reference || "Not provided"}</p>{result.endpoint_id && <Button size="sm" variant="outline" onClick={()=>setTrace(result.endpoint_id!)}>Request trace</Button>}</div>)}</div>}
 <CoverageItemsDialog scanId={scanId} metric={metric} onClose={()=>setMetric(null)} onTrace={id=>{setMetric(null);setTrace(id)}}/>
 <EndpointTraceDialog scanId={scanId} endpointId={trace} onClose={()=>setTrace(null)}/>

 <p className="text-xs text-muted-foreground">{(proof.not_tracked ?? []).map(metric=>`${metric.replaceAll("_"," ")}: NOT TRACKED`).join(" · ")}</p>
 {(proof.definitions ?? []).map(definition=><p className="text-xs" key={definition.id}>{definition.kind} · {definition.state} · {definition.url} {definition.reason}</p>)}
 {(proof.discovery_gaps ?? []).map((gap,i)=><p className="text-xs text-muted-foreground" key={i}>Discovery gap: {gap}</p>)}
 {discovery.data && discovery.data.candidates.length>0 && <div className="space-y-2 border-t pt-3"><p className="text-sm font-medium">Review discovered destinations</p><p className="text-xs text-muted-foreground">These candidates are outside the accepted plan. Credentials are not copied to new targets.</p>{discovery.data.candidates.map(candidate=><label className="flex items-center gap-2 text-xs" key={candidate.id}><input type="checkbox" checked={selected.includes(candidate.id)} onChange={e=>setSelected(values=>e.target.checked?[...values,candidate.id]:values.filter(id=>id!==candidate.id))}/><span>{candidate.value} · {candidate.kind} · {candidate.source}{candidate.actions?.map(action=><span className="mt-1 block text-muted-foreground" key={action.scanner}>{action.scanner}: {action.description}</span>)}</span></label>)}<Button size="sm" disabled={running||selected.length===0||approval.isPending} onClick={()=>approval.mutate()}>Approve and preview revised plan</Button>{running&&<p className="text-xs text-muted-foreground">Accepted jobs can finish before a revised plan starts.</p>}</div>}
 {revision&&<div className="space-y-2 border-t pt-3"><p className="text-sm font-medium">Approved revision</p><p className="break-all text-xs text-muted-foreground">{revision.plan.fingerprint}</p>{revision.plan.jobs?.map(job=><p className="text-xs" key={job.id}>{job.scanner}{job.auth_identity ? ` · ${job.auth_identity}` : ""} · {job.target} · {job.state} · {job.reason}</p>)}<Button size="sm" disabled={start.isPending||!!started} onClick={()=>start.mutate()}>Start approved revision</Button></div>}
 {(approval.error||start.error)&&<p role="alert" className="text-xs text-destructive">{(approval.error||start.error)?.message}</p>}{started&&<p className="text-xs">Approved revision queued: {started}</p>}
 </CardContent></Card>;
}

export function EndpointTraceDialog({scanId,endpointId,onClose}:{scanId:string;endpointId:string|null;onClose:()=>void}) {
 const [page,setPage]=useState(1);
 const result=useQuery({queryKey:["endpoint-trace",scanId,endpointId,page],queryFn:()=>api.endpointTrace(scanId,endpointId!,page),enabled:!!endpointId});
 return <Dialog open={!!endpointId} onOpenChange={open=>{if(!open){setPage(1);onClose()}}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>Endpoint evidence trace</DialogTitle></DialogHeader>
 {result.error&&<p role="alert">{result.error.message}</p>}{result.data&&<div className="space-y-3 text-xs"><p className="break-all font-mono">{result.data.endpoint.method} {result.data.endpoint.url}</p><p>Evidence: {result.data.state}</p>{result.data.endpoint.coverage_history?.map((entry,i)=><p key={i}>{entry.scanner} · {entry.status} · attempt {entry.attempt_id??"NOT TRACKED"} · {entry.reason}</p>)}{(result.data.items ?? []).map((event,i)=><div className="rounded border p-2" key={i}><p>{event.scanner} · {event.phase} · {event.kind} · {event.response_code??""}</p><p>{event.at} · attempt {event.attempt_id}</p><p>{event.reason}</p></div>)}<div className="flex gap-2"><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><Button size="sm" variant="outline" disabled={page*25>=result.data.total} onClick={()=>setPage(page+1)}>Next</Button></div></div>}
 </DialogContent></Dialog>;
}

function CoverageItemsDialog({scanId,metric,onClose,onTrace}:{scanId:string;metric:{name:string;scanner?:string;label:string}|null;onClose:()=>void;onTrace:(id:string)=>void}){
 const [page,setPage]=useState(1);
 useEffect(()=>setPage(1),[metric?.name,metric?.scanner]);
 const result=useQuery({queryKey:["coverage-items",scanId,metric?.name,metric?.scanner,page],queryFn:()=>api.coverageItems(scanId,metric!.name,metric!.scanner,page),enabled:!!metric});
 return <Dialog open={!!metric} onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{metric?.label}</DialogTitle></DialogHeader>{result.error&&<p role="alert">{result.error.message}</p>}{result.data&&<div className="space-y-3 text-xs"><p>{result.data.total} saved inventory or evidence items</p>{(result.data.items ?? []).map(item=><div className="space-y-1 rounded border p-2" key={item.id}><p className="break-all font-mono">{item.method} {item.url||item.id}</p><p>{item.state} {item.reason}</p>{item.attempt_id&&<p>Attempt: {item.attempt_id}</p>}{item.evidence_reference&&<p className="break-all">Evidence: {item.evidence_reference}</p>}{item.endpoint_id&&<Button size="sm" variant="outline" onClick={()=>onTrace(item.endpoint_id!)}>Request trace</Button>}</div>)}<div className="flex gap-2"><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><Button size="sm" variant="outline" disabled={page*25>=result.data.total} onClick={()=>setPage(page+1)}>Next</Button></div></div>}</DialogContent></Dialog>
}
