import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Activity, AlertTriangle, CheckCircle2, ChevronRight, Plus, Server } from "lucide-react";
import { api } from "@/api/client";
import { useScansList } from "@/api/queries";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MetricCard } from "@/components/metric-card";
import { ScanStatusPill } from "@/components/scan-status-pill";
import type { FindingsSummaryResponse } from "@/types/api";

export default function OverviewPage() {
  const scans = useScansList();
  const health = useQuery({ queryKey: ["scanner-status"], queryFn: api.scannerStatus, refetchInterval: 30000 });
  const summary = useQuery({ queryKey: ["findings", "summary"], queryFn: async () => { const response = await fetch("/api/findings/summary", { credentials: "same-origin" }); if (!response.ok) throw new Error("Unable to load findings summary"); return (await response.json()) as FindingsSummaryResponse; }, refetchInterval: 15000 });
  const items = scans.data ?? [];
  const scannerHealth = health.data?.scanners ?? [];
  const available = scannerHealth.filter((s) => s.available).length;
  const running = items.filter((s) => ["running", "pending", "paused"].includes((s.status || "").toLowerCase())).length;
  const totals = summary.data?.totals ?? { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  const attention = items.filter((s) => ["failed", "stopped"].includes((s.status || "").toLowerCase())).length;
  return <div className="space-y-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Security workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Overview</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">See what is running, what needs attention, and where your latest assessment found risk.</p></div><Button asChild><Link to="/scans/new"><Plus className="h-4 w-4" /> New assessment</Link></Button></header>
    <section aria-label="Workspace summary" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Active assessments" value={running} hint={running ? "Currently running or paused" : "No assessments in progress"} icon={<Activity className="h-4 w-4" />} to="/scans" accent={running ? "warning" : "default"} /><MetricCard label="Active findings" value={summary.data?.active_security_findings ?? "—"} hint={`${summary.data?.unique_findings ?? 0} unique · ${summary.data?.raw_observations ?? 0} observations`} icon={<AlertTriangle className="h-4 w-4" />} to="/findings" accent={(totals.critical + totals.high) > 0 ? "critical" : "default"} /><MetricCard label="Scanners ready" value={`${available}/${scannerHealth.length || "—"}`} hint="Tool availability" icon={<Server className="h-4 w-4" />} to="/settings" /><MetricCard label="Needs attention" value={attention} hint={attention ? "Failed or stopped assessments" : "Everything is on track"} icon={<CheckCircle2 className="h-4 w-4" />} to="/scans" accent={attention ? "warning" : "success"} /></section>
    <section className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><Card><CardHeader className="flex flex-row items-center justify-between space-y-0"><div><CardTitle>Risk snapshot</CardTitle><p className="mt-1 text-xs text-muted-foreground">Unique active findings by severity</p></div><Link className="text-xs text-muted-foreground hover:text-foreground" to="/findings">View findings <ChevronRight className="inline h-3 w-3" /></Link></CardHeader><CardContent><div className="grid grid-cols-5 gap-2">{([['Critical', totals.critical, 'text-red-400'], ['High', totals.high, 'text-orange-400'], ['Medium', totals.medium, 'text-amber-400'], ['Low', totals.low, 'text-blue-400'], ['Info', totals.info, 'text-muted-foreground']] as const).map(([label, value, color]) => <div key={label} className="rounded-lg border bg-muted/10 p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-2 text-2xl font-semibold tabular-nums ${color}`}>{value}</p></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Scanner health</CardTitle><p className="mt-1 text-xs text-muted-foreground">Availability is checked periodically.</p></CardHeader><CardContent className="space-y-2">{scannerHealth.slice(0, 6).map((s) => <div key={s.name} className="flex items-center justify-between rounded-md border px-3 py-2"><div className="min-w-0"><p className="truncate text-sm font-medium capitalize">{s.name}</p><p className="text-[10px] uppercase text-muted-foreground">{s.phase === "sast" ? "source code" : s.phase}</p></div><span className={`text-xs ${s.available ? "text-emerald-400" : "text-red-400"}`}>{s.available ? "Ready" : "Unavailable"}</span></div>)}{!scannerHealth.length && <p className="text-sm text-muted-foreground">Scanner status is unavailable.</p>}</CardContent></Card></section>
    <Card><CardHeader className="flex flex-row items-center justify-between space-y-0"><div><CardTitle>Recent assessments</CardTitle><p className="mt-1 text-xs text-muted-foreground">Open an assessment to review coverage, evidence, and logs.</p></div><Link className="text-xs text-muted-foreground hover:text-foreground" to="/scans">View all <ChevronRight className="inline h-3 w-3" /></Link></CardHeader><CardContent className="p-0"><div className="divide-y divide-border">{items.slice(0, 8).map((s) => <Link key={s.id} to={`/scans/${s.id}`} className="flex items-center gap-4 px-5 py-3.5 transition-colors hover:bg-muted/20"><div className="min-w-0 flex-1"><p className="truncate font-mono text-sm">{s.target}</p><p className="mt-1 text-xs text-muted-foreground">{s.scan_mode || "single"} · {new Date(s.started_at).toLocaleString()}</p></div><span className="hidden text-xs text-muted-foreground sm:inline">{s.vuln_count ?? 0} findings</span><ScanStatusPill status={s.status} /><ChevronRight className="h-4 w-4 text-muted-foreground" /></Link>)}{!items.length && <div className="p-10 text-center text-sm text-muted-foreground">No assessments yet. Start one to populate your workspace.</div>}</div></CardContent></Card>
  </div>;
}
